runtime: python312

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: 'production'

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
